eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8081/eureka/
server:
  port: 8765
  #context-path: /feign
spring:
  application:
    name: service-feign
feign:
  hystrix:
    enabled: true